# -*- coding: utf-8 -*-
"""Lab4-2_Music Playlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJ9DnyF8Rqc9ZzKyfCJ4U84jj6sf-_IC

#Lab4-2 การนำ Linked List มาใช้งาน

### Music Playlist

First, let's define the `Song` class. Each `Song` object will represent a node in our linked list, containing song details and a pointer to the next song.
"""

class Song:
    def __init__(self, title, artist):
        self.title = title
        self.artist = artist
        self.next_song = None

    def __str__(self):
        return f"{self.title} by {self.artist}"

"""Next, we'll define the `MusicPlaylist` class, which will manage the collection of `Song` objects using a linked list. It will have methods to add songs, display the playlist, and optionally play songs (though 'playing' here is just printing the song details)."""

class MusicPlaylist:
    def __init__(self):
        self.head = None  # The head of the linked list (first song)
        self.current_song = None # To keep track of the currently playing song
        self.length = 0

    def add_song(self, title, artist):
        new_song = Song(title, artist)
        if self.head is None:
            self.head = new_song
            self.current_song = new_song # If first song, it's also the current one
        else:
            current = self.head
            while current.next_song:
                current = current.next_song
            current.next_song = new_song
        self.length += 1
        print(f"Added: {new_song}")

    def display_playlist(self):
        if self.head is None:
            print("Playlist is empty.")
            return

        current = self.head
        print("\n--- Your Music Playlist ---")
        count = 1
        while current:
            print(f"{count}. {current}")
            current = current.next_song
            count += 1
        print("---------------------------")

    def play_current_song(self):
        if self.current_song:
            print(f"\nNow playing: {self.current_song}")
        else:
            print("Playlist is empty or no song is selected to play.")

    def next_song(self):
        if self.current_song and self.current_song.next_song:
            self.current_song = self.current_song.next_song
            self.play_current_song()
        elif self.current_song and not self.current_song.next_song:
            print("End of playlist. No next song.")
        else:
            print("Playlist is empty.")

    def prev_song(self):
        if self.head is None or self.current_song is None:
            print("Playlist is empty or no song is selected.")
            return
        if self.current_song == self.head:
            print("Already at the beginning of the playlist.")
            return

        current = self.head
        while current.next_song != self.current_song:
            current = current.next_song
        self.current_song = current
        self.play_current_song()

    def get_length(self):
        return self.length

    def delete_song(self, title):
        if self.head is None:
            print(f"Cannot delete '{title}'. Playlist is empty.")
            return

        # If the song to be deleted is the head
        if self.head.title == title:
            if self.current_song == self.head:
                self.current_song = self.head.next_song
            self.head = self.head.next_song
            self.length -= 1
            print(f"Deleted: {title}")
            if self.length == 0:
                self.current_song = None
            return

        current = self.head
        prev = None
        while current and current.title != title:
            prev = current
            current = current.next_song

        if current:
            if self.current_song == current:
                # If the deleted song was the current song, try to set the next song as current
                # If no next, then previous. If no previous, then current becomes None.
                if current.next_song:
                    self.current_song = current.next_song
                elif prev:
                    self.current_song = prev
                else:
                    self.current_song = None # Only one song, and it was deleted

            prev.next_song = current.next_song
            self.length -= 1
            print(f"Deleted: {title}")
        else:
            print(f"Song '{title}' not found in the playlist.")

"""Now, let's demonstrate how to use these classes to create and manage a music playlist."""

# Create a new playlist
my_playlist = MusicPlaylist()

# Add some songs
my_playlist.add_song("Bohemian Rhapsody", "Queen")
my_playlist.add_song("Stairway to Heaven", "Led Zeppelin")
my_playlist.add_song("Hotel California", "Eagles")
my_playlist.add_song("Imagine", "John Lennon")

# Display the entire playlist
my_playlist.display_playlist()

# Play the current song (which should be the first one added)
my_playlist.play_current_song()

# Move to the next song and play it
my_playlist.next_song()

# Move to the next song again
my_playlist.next_song()

# Go back to the previous song
my_playlist.prev_song()

# Try to go back again (should indicate already at beginning)
my_playlist.prev_song()

# Move to the end of the playlist
my_playlist.next_song()
my_playlist.next_song()
my_playlist.next_song()

# Try to move next from the end
my_playlist.next_song()

# Check playlist length
print(f"\nPlaylist length: {my_playlist.get_length()} songs")

# Delete a song that exists
my_playlist.delete_song("Stairway to Heaven")
my_playlist.delete_song("Hotel California")
my_playlist.display_playlist()

# Play the current song (which should be the first one added)
my_playlist.play_current_song()

# Try to move next from the end
my_playlist.next_song()

# Check playlist length
print(f"\nPlaylist length: {my_playlist.get_length()} songs")

"""#สร้าง Web App

1. installing **streamlit** and **pyngrok** libraries
"""

pip install streamlit pyngrok

"""2. สร้างไฟล์ .py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(page_title="Music Playlist App", layout="wide")
# 
# # ===== Session State =====
# if "playlist" not in st.session_state:
#     st.session_state.playlist = []
# 
# if "current" not in st.session_state:
#     st.session_state.current = None
# 
# # ===== Sidebar =====
# st.sidebar.header("Add New Song")
# 
# title = st.sidebar.text_input("Title")
# artist = st.sidebar.text_input("Artist")
# audio = st.sidebar.file_uploader(
#     "Upload Audio File (Optional)",
#     type=["mp3", "wav", "ogg"]
# )
# 
# if st.sidebar.button("Add Song to Playlist"):
#     if title and artist and audio:
#         st.session_state.playlist.append({
#             "title": title,
#             "artist": artist,
#             "audio": audio
#         })
#         st.sidebar.success("Song added!")
#     else:
#         st.sidebar.warning("Please fill all fields")
# 
# st.sidebar.markdown("---")
# st.sidebar.header("Delete Song")
# delete_title = st.sidebar.text_input("Song Title to Delete")
# 
# if st.sidebar.button("Delete Song"):
#     st.session_state.playlist = [
#         s for s in st.session_state.playlist
#         if s["title"] != delete_title
#     ]
#     st.sidebar.success("Song deleted (if existed)")
# 
# # ===== Main Content =====
# st.markdown("## 🎵 Music Playlist App")
# st.markdown("### Your Current Playlist")
# 
# if len(st.session_state.playlist) == 0:
#     st.info("Playlist is empty. Add some songs from the sidebar!")
# else:
#     if st.session_state.current is None:
#         st.session_state.current = 0
# 
#     song = st.session_state.playlist[st.session_state.current]
#     st.write(f"**{song['title']}** - {song['artist']}")
# 
# st.markdown("---")
# st.markdown("### Playback Controls")
# 
# col1, col2, col3 = st.columns(3)
# 
# with col1:
#     if st.button("⏮ Previous"):
#         if st.session_state.current is not None and st.session_state.current > 0:
#             st.session_state.current -= 1
# 
# with col2:
#     if st.button("▶ Play Current"):
#         if st.session_state.current is None or len(st.session_state.playlist) == 0:
#             st.warning("Playlist is empty or no song is selected to play.")
#         else:
#             st.audio(st.session_state.playlist[st.session_state.current]["audio"])
# 
# with col3:
#     if st.button("⏭ Next"):
#         if (
#             st.session_state.current is not None
#             and st.session_state.current < len(st.session_state.playlist) - 1
#         ):
#             st.session_state.current += 1
# 
# st.markdown("---")
# st.write(f"Total songs in playlist: {len(st.session_state.playlist)} song(s)")
#

"""3. Login **ngrok** ที่ https://ngrok.com/ and copy your **authtoken**"""

!ngrok authtoken 36GtzKHFSvDFaJjG4bhRh7hkeNT_5q9gcBoZrnJCfhvJFRs5W

from pyngrok import ngrok

ngrok.kill()  # ปิด tunnel เก่า

public_url = ngrok.connect(8501)
print("🌍 Open your app here:", public_url)

"""4. **รัน app Streamlit** ที่สร้างขึ้นมา
การบอกให้ Colab รันไฟล์ calculator.py ด้วย Streamlit บนพอร์ต 8501
"""

!streamlit run app.py --server.port 8501 &